site_name: Interfaces - Documentação
pages:
    - Interoperabilidade: index.md
    - Catálogo de serviços: services.md
    - GH: gh.md
    - BST - Bedside Tracker: bst.md
    - BPOC: bpoc.md
    - Especificação HL7: hl7.md
    - About: about.md
theme: readthedocs